---
title: "Meeting Notes 12/3"
author: "Chansoo Song"
date: "11/12/2018"
output: pdf_document
---

```{r setup, include=FALSE,warning=FALSE,message=FALSE}
library(dplyr)
library(plyr)
library(lme4)
library(nlme)
library(car)
library(ggplot2)
```

```{r}
load('../data/plot_list.RDATA')
plot_list[[1]]
plot_list[[2]]
plot_list[[3]]
plot_list[[4]]
plot_list[[5]]
plot_list[[6]]
plot_list[[7]]
plot_list[[8]]
plot_list[[9]]
plot_list[[10]]
plot_list[[11]]
plot_list[[12]]
plot_list[[13]]
plot_list[[14]]
plot_list[[15]]
```

```{r}
# Read Data
# master = read.csv('../data/master.csv')
# master = master %>% mutate(ellpercent = ell/total.enrollment,
#                            disabledpercent = disabled/total.enrollment)
# missing_data = which(apply(is.na(master[,c('povertypercent','disabledpercent','ellpercent','asianpercent','blackpercent','hispanicpercent','district','dbn','mean.scale.score')]),1,sum)>0)
# master = master[-missing_data,]
# 
# df = master %>%
#   filter(math == 1,
#          grade < 6,
#          charter == 0)
# 
# df$charter_count = (df$charter_count - mean(df$charter_count))/sd(df$charter_count)
```


Data Dictionary:
 [1] "DBN": School ID                                     
 [2] "Grade"                                   
 [3] "Year"                                    
 [4] "Number.Tested": Number of Students in Grade X, Year Y, School Z                           
 [5] "Mean.Scale.Score": Mean Score of Students in Grade X, Year Y, School Z
 [6] "charter": Indicator for Charter School
 [7] "math": Indicator for Math vs ELA                                    
 [8] "district": School District Code              
 [9] "NTA": Neighborhood Tabulation Area                                     
[10] "NTA_NAME"                                
[11] "CENSUS_TRACT"                            
[12] "Location.1"                              
[13] "Poverty": Number of Students in Poverty Status                                 
[14] "Disabled": Number of Students with Disabled Status                                
[15] "Ell": Number of Students in ELL                                     
[16] "esid_no": School Zone ID                                 
[17] "Total.Enrollment"                        
[18] "Asian"                                   
[19] "Black"                                   
[20] "Hispanic"                                
[21] "White"                                   
[22] "shannon": Shannon Entropy Index measure of Diversity                                 
[23] "shannon_nta": Shannon Entropy Index at NTA level                             
[24] "shannon_cd": Shannon Entorpy Index at School District level                              
[25] "year_sch": Concatenation of Year and School                                
[26] "GradeYear": Concatenation of Grade and Year                               
[27] "charter_count": Share of Charter schools in School Zone in year X                           
[28] "charter_share": Number of Charter schools in School Zone in year X                           
[29] "charter_count_district": Number of Charter schools in School District in year X              
[30] "charter_share_district": Share of Charter schools in School District in year X              
[31] "charter_score": Average score of Charter schools at School Zone level in year X                            
[32] "cohort": The year that the grade started 3rd Grade                                  
[33] "new": Number of New Charter Schools since the previous year in school zone

```{r}
# Load Saved Models
load('models.RDATA')
```

```{r}
# Unconditional Means Model
##############################
# um.mod = lmer(mean.scale.score ~ (1 | district/dbn/cohort), data = df)
um.mod.vars = as.data.frame(VarCorr(um.mod))
um.mod.vars$vcov[1] / sum(um.mod.vars$vcov) # ICC cohort
um.mod.vars$vcov[2] / sum(um.mod.vars$vcov) # ICC zone
um.mod.vars$vcov[3] / sum(um.mod.vars$vcov) # ICC district

# 20.6% of variation is between cohorts 
# 36.7% of variation is between zones
# 32.3% of variation is between districts
```


```{r}
# Add Treatment Covariate + Random Slope
##############################
# mod1 = lmer(mean.scale.score ~ charter_count + (1 | district/dbn), data = df)
# mod2 = lmer(mean.scale.score ~ charter_count + (charter_count | district/dbn), data = df)
summary(mod1)
summary(mod2)
anova(mod1,mod2,refit=F)
```

```{r}
# Add Demographics
##############################
# mod3 = lmer(mean.scale.score ~ charter_count + povertypercent + disabledpercent + ellpercent + asianpercent + blackpercent + hispanicpercent +
#                  (charter_count | district/dbn), data = df)
summary(mod3)
anova(mod1,mod2,mod3,refit=F)
```

```{r}
# Add new_charts, cohort, year
##############################
# mod4 = lmer(mean.scale.score ~ charter_count + povertypercent + disabledpercent + ellpercent + asianpercent + blackpercent + hispanicpercent + new_charts +
#               (charter_count | district/dbn), data = df)
# mod5 = lmer(mean.scale.score ~ charter_count + povertypercent + disabledpercent + ellpercent + asianpercent + blackpercent + hispanicpercent + new_charts + cohort +
#               (charter_count | district/dbn), data = df)
# mod6 = lmer(mean.scale.score ~ charter_count + povertypercent + disabledpercent + ellpercent + asianpercent + blackpercent + hispanicpercent +
#               new_charts + cohort + year + (charter_count | district/dbn), data = df)
anova(mod3,mod4,mod5,mod6,refit=F)

plot(density(residuals(mod6)))
qqnorm(residuals(mod6))
qqline(residuals(mod6))
```

```{r}
# Try nlme
# mod7 = lme(mean.scale.score ~ year, random=~year|district, data = df, correlation=corAR1())
# mod8 failed to converge
# mod8 = lme(mean.scale.score ~ charter_count + povertypercent + disabledpercent + ellpercent + asianpercent + blackpercent + hispanicpercent + 
#              new_charts + cohort + year,
#            random=~year+charter_count|district/dbn, 
#            data = df, 
#            correlation=corAR1())
summary(mod7)
```

```{r}
# save(um.mod,mod1,mod2,mod3,mod4,mod5,mod6,mod7,file='models.RDATA')
```

```{r}
# Did not run:
# mod7 = lmer(mean.scale.score ~ year + (year | district), data = df)
# mod8 = lmer(mean.scale.score ~ year + (year || district) + (0 + year | district:dbn), data = df)
# summary(mod6)
# summary(mod7)
```